# Embeddings

In [2]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [3]:
text = ["car","vehicle","banana"]

sentence = model.encode(text)

In [8]:
i = 0
for s in sentence:
    print(f"encoding of text {text[i]} -> {s}")
    i+=1

encoding of text car -> [-3.32785323e-02  1.05793066e-01  1.88690014e-02  5.19480295e-02
 -3.74658816e-02  3.12398225e-02  1.22579403e-01  4.23529297e-02
  4.18527834e-02 -4.69678640e-02  4.40441370e-02 -1.55207161e-02
 -4.20483440e-04 -5.27277868e-03 -3.42085734e-02 -3.23650278e-02
 -2.06108764e-02 -4.37611751e-02 -7.40345940e-02 -2.17037108e-02
 -3.80415283e-02  3.91215682e-02 -8.80705193e-03  1.59312133e-02
 -5.20220287e-02  7.72779211e-02 -5.06950207e-02  5.17847165e-02
  1.06467856e-02 -1.08625546e-01 -1.37945246e-02  1.48111358e-02
  7.96726346e-03 -2.41638124e-02 -5.50028272e-02 -9.58886221e-02
  6.15943270e-03 -2.60683559e-02  3.37703861e-02 -4.28532548e-02
 -1.24670491e-02 -1.17915012e-01 -6.41183788e-03 -1.51643036e-02
  2.30925735e-02  7.58101523e-04  1.09412141e-01  5.19213900e-02
  8.99717584e-02 -4.74752337e-02 -5.04657067e-02  6.95853075e-03
 -6.00864254e-02  6.51159696e-03 -7.79590979e-02  9.27387923e-03
 -3.55442837e-02  7.14655519e-02 -3.28454562e-02  5.61602274e-03
 

# Cosine Similarity

In-built Function

In [ ]:
print(util.cos_sim(sentence[0],sentence[1])) # car --> vehicle
print(util.cos_sim(sentence[0],sentence[2])) # car --> banana
print(util.cos_sim(sentence[1],sentence[2])) # vehicle --> banana

tensor([[0.8704]])
tensor([[0.8704]])
tensor([[0.8645]])
tensor([[0.8471]])


Manual Implementation

In [9]:
def cosine_similarity(emb_a,emb_b):
    dot = np.dot(emb_a,emb_b)
    norm_a = np.linalg.norm(emb_a)
    norm_b = np.linalg.norm(emb_b)
    return dot / (norm_a * norm_b)

In [15]:

import pandas
texts = [
    "car",
    "vehicle",
    "automobile",
    "truck",
    "banana",
    "apple",
    "fruit"
]

sentence = model.encode(texts)
matrix = util.cos_sim(sentence, sentence)
data = pandas.DataFrame(matrix,columns=texts,index=texts)
print(data)

                 car   vehicle  automobile     truck    banana     apple  \
car         1.000000  0.870427    0.864528  0.688680  0.389886  0.409820   
vehicle     0.870427  1.000000    0.847137  0.765543  0.310639  0.308338   
automobile  0.864528  0.847137    1.000000  0.672308  0.273755  0.378979   
truck       0.688680  0.765543    0.672308  1.000000  0.356022  0.314308   
banana      0.389886  0.310639    0.273755  0.356022  1.000000  0.424048   
apple       0.409820  0.308338    0.378979  0.314308  0.424048  1.000000   
fruit       0.425512  0.362852    0.369927  0.322937  0.726050  0.537244   

               fruit  
car         0.425512  
vehicle     0.362852  
automobile  0.369927  
truck       0.322937  
banana      0.726050  
apple       0.537244  
fruit       1.000000  


In [16]:
documents = ["I am currently reading Can't hurt by David Goggins. It tell you how to master your mind and face challenges, give your fullest effort.",
             "I'm currently learning topics related to AI engineer to get placed in some top product based mnc's."]
embeddings = model.encode(documents)

query = "I'm working hard to achive my dream job"
query_emb = model.encode(query)

print(util.cos_sim(query_emb,embeddings))

tensor([[0.2492, 0.2827]])


In [17]:
text = ["challenges","difficulties"]
emb = model.encode(text)
print(util.cos_sim(emb[0],emb[1]))

tensor([[0.7082]])


In [18]:
text = ["challenges","difficulties"]
emb = model.encode(text)
import numpy as np
dot = np.dot(emb[0],emb[1])
print("dot product between 2 vector:",dot)
norm_a = np.linalg.norm(emb[0])
norm_b = np.linalg.norm(emb[1])
print("norm of vector a:",norm_a)
print("norm of vector b:",norm_b)
cos_sim = dot / (norm_a * norm_b)
print(cos_sim)

dot product between 2 vector: 0.7081604
norm of vector a: 1.0
norm of vector b: 1.0
0.7081604


# Tokenization

In [ ]:
import tiktoken
model = tiktoken
enc = tiktoken.get_encoding("gpt2")
print(enc.encode("hello world!!!"))
# for i in enc.encode("hello world!!!"):
#   print(enc.decode([i]))

token = enc.encode("Many common characters, including numerals, punctuation, and other symbols, are unified within the standard and are not treated as specific to any given writing system. Unicode encodes thousands of emoji, with the continued development thereof conducted by the Consortium as a part of the standard.[4] Moreover, the widespread adoption of Unicode was in large part responsible for the initial popularization of emoji outside of Japan. Unicode is ultimately capable of encoding more than 1.1 million characters.")
for i in token:
  print(enc.decode([i]))



[31373, 995, 10185]
Many
 common
 characters
,
 including
 numer
als
,
 punct
uation
,
 and
 other
 symbols
,
 are
 unified
 within
 the
 standard
 and
 are
 not
 treated
 as
 specific
 to
 any
 given
 writing
 system
.
 Unicode
 enc
odes
 thousands
 of
 emoji
,
 with
 the
 continued
 development
 thereof
 conducted
 by
 the
 Consortium
 as
 a
 part
 of
 the
 standard
.[
4
]
 Moreover
,
 the
 widespread
 adoption
 of
 Unicode
 was
 in
 large
 part
 responsible
 for
 the
 initial
 popular
ization
 of
 emoji
 outside
 of
 Japan
.
 Unicode
 is
 ultimately
 capable
 of
 encoding
 more
 than
 1
.
1
 million
 characters
.


In [ ]:
import tiktoken

enc = tiktoken.get_encoding("cl100k_base")

text = "unbelievable"

tokens = enc.encode(text)

print(tokens)
print(len(tokens))

[359, 32898, 24694]
3


Comparison of Multiple embedding model

In [1]:
from sentence_transformers import SentenceTransformer

# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

sentences = [
    "I love machine learning",
    "Artificial intelligence is fascinating",
    "I ate pizza for lunch"
]

embeddings = model.encode(sentences)

print(embeddings.shape)


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

(3, 384)


In [2]:
query = "What are the advancements in NLP?"
documents = [
    "Machine learning enables advancements in NLP.",
    "Climate change is a pressing issue globally.",
    "Natural language processing allows machines to understand text."
]

In [5]:
from sentence_transformers import SentenceTransformer,util
#Model 1 --> BGE
model_bge = SentenceTransformer("BAAI/bge-large-en-v1.5")
query_emb = model_bge.encode(query)
doc_emb = model_bge.encode(documents)

similarity = util.cos_sim(query_emb, doc_emb)
print("sequence length:",model_bge.get_sentence_embedding_dimension())
print(similarity)

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

sequence length: 1024
tensor([[0.7793, 0.4073, 0.6486]])


/tmp/ipykernel_6833/1664470161.py:8: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print("sequence length:",model_bge.get_sentence_embedding_dimension())


In [7]:
from sentence_transformers import SentenceTransformer

# Load the 'e5-large-v2' model
model_e5 = SentenceTransformer('intfloat/e5-large-v2')
query_emb = model_e5.encode(query)
doc_emb = model_e5.encode(documents)

print("sequence length:",model_e5.get_sentence_embedding_dimension())
similarity = util.cos_sim(query_emb, doc_emb)
print(similarity)

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

sequence length: 1024
tensor([[0.9171, 0.7275, 0.8359]])


/tmp/ipykernel_6833/1122268798.py:8: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print("sequence length:",model_e5.get_sentence_embedding_dimension())


In [21]:
from sentence_transformers import SentenceTransformer,util

model_mpnet = SentenceTransformer("sentence-transformers/multi-qa-mpnet-base-dot-v1")
query_emb = model_mpnet.encode(query)
doc_emb = model_mpnet.encode(documents)

print("sequence length:",model_mpnet.get_sentence_embedding_dimension())
similarity = util.cos_sim(query_emb, doc_emb)
print(similarity)
result = util.semantic_search(query_emb, doc_emb,top_k=1)
print(result)
print(documents[result[0][0]['corpus_id']])

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

sequence length: 768
tensor([[0.7771, 0.3897, 0.5869]])
[[{'corpus_id': 0, 'score': 0.777096152305603}]]
Machine learning enables advancements in NLP.


/tmp/ipykernel_6833/3686627184.py:7: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print("sequence length:",model_mpnet.get_sentence_embedding_dimension())


In [19]:
from sentence_transformers import SentenceTransformer,util
import numpy

model_qwen = SentenceTransformer("Qwen/Qwen3-VL-Embedding-2B")
query_embedding = model_qwen.encode(
        query,
        convert_to_tensor=True
    )

doc_embeddings = model_qwen.encode(
    documents,
    convert_to_tensor=True
)

similarities = util.cos_sim(
    query_embedding,
    doc_embeddings
)[0]

# Convert to float32 before converting to numpy to handle BFloat16
scores = similarities.cpu().float().numpy()

ranked = sorted(
    zip(documents, scores),
    key=lambda x: x[1],
    reverse=True
)

print("\nSimilarity Scores:\n")

for doc, score in ranked:
    print(f"{score:.4f} -> {doc}")

print("\nTop Retrieved Document:")
print(ranked[0][0])

Loading weights:   0%|          | 0/625 [00:00<?, ?it/s]


Similarity Scores:

0.8516 -> Machine learning enables advancements in NLP.
0.6758 -> Natural language processing allows machines to understand text.
0.4199 -> Climate change is a pressing issue globally.

Top Retrieved Document:
Machine learning enables advancements in NLP.


TF-IDF Manual Implementation

In [1]:
import numpy as np

corpus = [
    "purple is the best city in the forest",
    "there is an art to getting your way and throwing bananas on to the street is not it",
    "it is not often you find soggy bananas on the street"
]

def tf_idf(query):
    tf_scores = []
    document_count = 0

    for doc in corpus:
        words = doc.split()
        term_count = words.count(query)

        if term_count > 0:
            document_count += 1

        tf_scores.append(term_count / len(words))

    if document_count == 0:
        print(f'"{query}" not found in the corpus.')
        return

    idf = np.log10(len(corpus) / document_count)

    print(f"TF-IDF scores for '{query}':")
    for score in tf_scores:
        print(round(score * idf, 2))

tf_idf("forest")

TF-IDF scores for 'forest':
0.06
0.0
0.0
